### ISSUE TITLE
Arguments Segregation

### ISSUE THREAD

**Issue by BMK91** [jowinjohnchemban/binwalk#1]
Hi,

You've provided the great solution but somehow script **binwalk.py** does not segregate arguments provided.
For instance,
`binwalk -e file.bin`
will execute like
`binwalk -efile.bin`
Which is not a valid one.

**Comment by BMK91** [comment]
```
strl = ' '.join(sys.argv[1:])
command = 'python "C:\\Program Files\\Python37\\Scripts\\binwalk" ' + strl
os.system(command)

```

**Comment by jowinjohnchemban** [comment]
Added

**Comment by jowinjohnchemban** [comment]
Merged
